title: "Vishal Chaudhary"
description: "Technical GRC & Security Architecture Consultant"

url: "https://vishsecurity.github.io"
baseurl: ""

markdown: kramdown
permalink: /blog/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
